name: "Validate Gradle Wrapper"
on: [push, pull_request, workflow_dispatch]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@main
        env:
          GRADLE_ACTION_ID: gradle/wrapper-validation-action

